// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/eraxyso/go-template/handler"
	"github.com/eraxyso/go-template/repository"
	"github.com/eraxyso/go-template/service"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeServer(db *gorm.DB) *handler.Handler {
	exampleRepositoryImpl := repository.NewExampleRepositoryImpl(db)
	exampleServiceImpl := service.NewExampleServiceImpl(exampleRepositoryImpl)
	middlewareServiceImpl := service.NewMiddlewareServiceImpl()
	handlerHandler := handler.NewHandler(exampleServiceImpl, middlewareServiceImpl)
	return handlerHandler
}

// wire.go:

var (
	exampleServiceBind = wire.Bind(
		new(service.ExampleService),
		new(*service.ExampleServiceImpl),
	)
	middlewareServiceBind = wire.Bind(
		new(service.MiddlewareService),
		new(*service.MiddlewareServiceImpl),
	)

	exampleRepositoryBind = wire.Bind(
		new(repository.ExampleRepository),
		new(*repository.ExampleRepositoryImpl),
	)
)
