// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/eraxyso/go-template/handler"
	"github.com/eraxyso/go-template/repository"
	"github.com/eraxyso/go-template/service"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeServer(db *gorm.DB) *handler.Handler {
	adminRepositoryImpl := repository.NewAdminRepositoryImpl(db)
	eventRepositoryImpl := repository.NewEventRepositoryImpl(db)
	middlewareServiceImpl := service.NewMiddlewareServiceImpl(adminRepositoryImpl, eventRepositoryImpl)
	attendeeRepositoryImpl := repository.NewAttendeeRepositoryImpl(db)
	eventServiceImpl := service.NewEventServiceImpl(eventRepositoryImpl, adminRepositoryImpl, attendeeRepositoryImpl)
	attendanceServiceImpl := service.NewAttendanceServiceImpl(attendeeRepositoryImpl)
	lotteryRepositoryImpl := repository.NewLotteryRepositoryImpl(db)
	winnerRepositoryImpl := repository.NewWinnerRepositoryImpl(db)
	lotteryServiceImpl := service.NewLotteryServiceImpl(lotteryRepositoryImpl, attendeeRepositoryImpl, winnerRepositoryImpl)
	handlerHandler := handler.NewHandler(middlewareServiceImpl, eventServiceImpl, attendanceServiceImpl, lotteryServiceImpl)
	return handlerHandler
}

// wire.go:

var (
	eventServiceBind = wire.Bind(
		new(service.EventService),
		new(*service.EventServiceImpl),
	)
	attendanceServiceBind = wire.Bind(
		new(service.AttendanceService),
		new(*service.AttendanceServiceImpl),
	)
	lotteryServiceBind = wire.Bind(
		new(service.LotteryService),
		new(*service.LotteryServiceImpl),
	)
	middlewareServiceBind = wire.Bind(
		new(service.MiddlewareService),
		new(*service.MiddlewareServiceImpl),
	)

	adminRepositoryBind = wire.Bind(
		new(repository.AdminRepository),
		new(*repository.AdminRepositoryImpl),
	)
	attendeeRepositoryBind = wire.Bind(
		new(repository.AttendeeRepository),
		new(*repository.AttendeeRepositoryImpl),
	)
	eventRepositoryBind = wire.Bind(
		new(repository.EventRepository),
		new(*repository.EventRepositoryImpl),
	)
	lotteryRepositoryBind = wire.Bind(
		new(repository.LotteryRepository),
		new(*repository.LotteryRepositoryImpl),
	)
	winnerRepositoryBind = wire.Bind(
		new(repository.WinnerRepository),
		new(*repository.WinnerRepositoryImpl),
	)
)
