/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/users/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 自分のtraQ IDを取得します */
    get: operations['getMe']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** イベントの一覧を取得します */
    get: operations['getEvents']
    put?: never
    /** 新しいイベントを作成します */
    post: operations['postEvent']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/events/{eventID}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 指定したイベントの詳細を取得します */
    get: operations['getEvent']
    put?: never
    post?: never
    /** 指定したイベントを削除します */
    delete: operations['deleteEvent']
    options?: never
    head?: never
    /** 指定したイベントの情報を更新します */
    patch: operations['patchEvent']
    trace?: never
  }
  '/events/{eventID}/attendance': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** 指定したイベントに出席登録を行います */
    post: operations['postAttendance']
    /** 指定したイベントの出席登録をキャンセルします */
    delete: operations['deleteAttendance']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/events/{eventID}/lotteries': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 指定したイベントの抽選の一覧を取得します */
    get: operations['getLotteries']
    put?: never
    /** 指定したイベントに対して新しい抽選を作成します */
    post: operations['postLottery']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/events/{eventID}/lotteries/{lotteryID}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** 指定した抽選の詳細を取得します */
    get: operations['getLottery']
    put?: never
    /** 指定した抽選を実行し、当選者を決定します */
    post: operations['rollLottery']
    /** 指定した抽選を削除します */
    delete: operations['deleteLottery']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    EventSummary: {
      /** Format: uuid */
      event_id: string
      title: string
      description: string
      /** Format: date */
      date: string
      is_open: boolean
      is_me_attendee: boolean
      admins: string[]
    }
    EventBase: {
      title: string
      description: string
      /** Format: date */
      date: string
      is_open: boolean
      is_me_attendee: boolean
      admins: string[]
      attendees: string[]
    }
    EventOnUpdate: {
      title: string
      description: string
      /** Format: date */
      date: string
      is_open: boolean
      admins: string[]
      attendees: string[]
    }
    Event: components['schemas']['EventBase'] & {
      /** Format: uuid */
      event_id: string
      is_deleted: boolean
      /** Format: date-time */
      updated_at: string
      /** Format: date-time */
      created_at: string
    }
    Lottery: {
      /** Format: uuid */
      lottery_id: string
      /** Format: uuid */
      event_id: string
      title: string
      is_deleted: boolean
      /** Format: date-time */
      created_at: string
      /** Format: date-time */
      updated_at: string
      winners: string[]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getMe: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            name?: string
          }
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  getEvents: {
    parameters: {
      query: {
        /** @description このパラメータが true の場合、削除済みのイベントも含めて取得します */
        ifDeleted: boolean
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EventSummary'][]
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  postEvent: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EventBase']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** Format: uuid */
            event_id?: string
          }
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  getEvent: {
    parameters: {
      query?: never
      header?: never
      path: {
        eventID: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Event']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  deleteEvent: {
    parameters: {
      query?: never
      header?: never
      path: {
        eventID: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  patchEvent: {
    parameters: {
      query?: never
      header?: never
      path: {
        eventID: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EventOnUpdate']
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  postAttendance: {
    parameters: {
      query?: never
      header?: never
      path: {
        eventID: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  deleteAttendance: {
    parameters: {
      query?: never
      header?: never
      path: {
        eventID: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  getLotteries: {
    parameters: {
      query: {
        /** @description このパラメータが true の場合、削除済みの抽選も含めて取得します */
        ifDeleted: boolean
      }
      header?: never
      path: {
        eventID: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Lottery'][]
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  postLottery: {
    parameters: {
      query?: never
      header?: never
      path: {
        eventID: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          title: string
        }
      }
    }
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** Format: uuid */
            lottery_id?: string
          }
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  getLottery: {
    parameters: {
      query?: never
      header?: never
      path: {
        eventID: string
        lotteryID: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Lottery']
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  rollLottery: {
    parameters: {
      query: {
        /** @description このパラメータが true の場合、同一イベント内での重複当選を許可します (false の場合も同一抽選内では重複当選は許可されません) */
        ifDuplicated: boolean
      }
      header?: never
      path: {
        eventID: string
        lotteryID: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            /** @description traQ ID */
            winner?: string
          }
        }
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  deleteLottery: {
    parameters: {
      query?: never
      header?: never
      path: {
        eventID: string
        lotteryID: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
}
