openapi: 3.0.4
info:
  title: API
  version: 0.0.0
servers:
  - url: https://localhost:2048
    description: Local server
tags:
  - name: Event
  - name: Attendance
  - name: Lottery
paths:
  /events:
    post:
      tags:
        - Event
      operationId: postEvents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventBase'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '500':
          description: Internal Server Error
    get:
      tags:
        - Event
      operationId: getEvents
      parameters:
        - in: query
          name: is_deleted
          schema:
            type: boolean
          description: If include the deleted events
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/EventSummary'
                  - type: object
                    properties:
                      event_id:
                        type: string
                        format: uuid
        '500':
          description: Internal Server Error
  /events/{eventID}:
    get:
      tags:
        - Event
      operationId: getEvent
      parameters:
        - in: path
          name: eventID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '500':
          description: Internal Server Error
    patch:
      tags:
        - Event
      operationId: patchEvent
      parameters:
        - in: path
          name: eventID
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventUpdate'
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Event
      operationId: deleteEvent
      parameters:
        - in: path
          name: eventID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /events/{eventID}/attendance:
    post:
      tags:
        - Attendance
      operationId: postAttendance
      parameters:
        - in: path
          name: eventID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Attendance
      operationId: deleteAttendance
      parameters:
        - in: path
          name: eventID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
  /events/{eventID}/lotteries:
    post:
      tags:
        - Lottery
      operationId: postLotteries
      parameters:
        - in: path
          name: eventID
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
              required:
                - title
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  lottery_id:
                    type: string
                    format: uuid
        '500':
          description: Internal Server Error
    get:
      tags:
        - Lottery
      operationId: getLotteries
      parameters:
        - in: path
          name: eventID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lottery'
        '500':
          description: Internal Server Error
  /events/{eventID}/lotteries/{lotteryID}:
    post:
      tags:
        - Lottery
      operationId: postLottery
      parameters:
        - in: path
          name: eventID
          required: true
          schema:
            type: string
            format: uuid
        - in: path
          name: lotteryID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  winner:
                    type: string
                    description: traQ ID
        '500':
          description: Internal Server Error
    get:
      tags:
        - Lottery
      operationId: getLottery
      parameters:
        - in: path
          name: eventID
          required: true
          schema:
            type: string
            format: uuid
        - in: path
          name: lotteryID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lottery'
        '500':
          description: Internal Server Error
    delete:
      tags:
        - Lottery
      operationId: deleteLottery
      parameters:
        - in: path
          name: eventID
          required: true
          schema:
            type: string
            format: uuid
        - in: path
          name: lotteryID
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
        '500':
          description: Internal Server Error
components:
  schemas:
    EventSummary:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        date:
          type: string
          format: date
        is_open:
          type: boolean
        is_me_attendee:
          type: boolean
        admins:
          type: array
          items:
            type: string
            description: traQ ID
      required:
        - title
        - date
        - is_open
        - is_me_attendee
        - admins
    EventBase:
      allOf:
        - $ref: '#/components/schemas/EventSummary'
        - type: object
          properties:
            attendees:
              type: array
              items:
                type: string
                description: traQ ID
          required:
            - attendees
    Event:
      allOf:
        - $ref: '#/components/schemas/EventBase'
        - type: object
          properties:
            event_id:
              type: string
              format: uuid
            is_deleted:
              type: boolean
            updated_at:
              type: string
              format: date-time
            created_at:
              type: string
              format: date-time
          required:
            - event_id
            - is_deleted
            - updated_at
            - created_at
    EventUpdate:
      allOf:
        - $ref: '#/components/schemas/EventBase'
        - type: object
          properties:
            is_deleted:
              type: boolean
          required:
            - is_deleted
    Lottery:
      type: object
      properties:
        lottery_id:
          type: string
          format: uuid
        event_id:
          type: string
          format: uuid
        title:
          type: string
        is_deleted:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        winners:
          type: array
          items:
            type: string
            description: traQ ID
      required:
        - lottery_id
        - event_id
        - title
        - is_deleted
        - updated_at
        - created_at
        - winners