openapi: "3.0.4"
info:
  title: "API Example"
  version: "0.0.0"
  description: "API description example."
servers:
  - url: "http://localhost:2048"
    description: "Local server"
tags:
  - name: "TagExample"
paths:
  /examples:
    post:
      tags:
        - "TagExample"
      operationId: "postExample"
      parameters:
        - name: "paramExample"
          in: "query"
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                requestBody:
                  type: string
      responses:
        '200':
          description: "OK"
        '500':
          description: "Internal Server Error"